BEGIN;

INSERT INTO bob_closed_items (id, framework, exam_part, cefr_level, variant_id, stimulus_audio_url, stimulus_text, stimulus_image_url, question, options, correct_key, explanation, source, created_at, skill, status, transcript, metadata)
VALUES
('4592a1f0-b62f-4c8e-98bf-1442c7cdf59a'::uuid, 'cefr', 'assessment_listening', 'b1', 'al-b1-03', '/listening/assessment/b1/al-b1-03.mp3', NULL, NULL, 'Why did the chef open a vegetarian restaurant?', '[{"key":"A","label":"Her family encouraged her"},{"key":"B","label":"She couldn''t find meat suppliers"},{"key":"C","label":"She saw a gap in the market"},{"key":"D","label":"She won a competition"}]'::jsonb, 'C', 'She says she "believed there was a real market for healthy, plant-based food."', 'generated_then_curated', '2026-05-18T17:30:16.407296+00:00'::timestamptz, 'listening', 'enabled', 'In this interview, a young chef explains why she chose to open a vegetarian restaurant. She says that although her family thought it was too risky, she believed there was a real market for healthy, plant-based food in her city. After two years, the restaurant is fully booked every weekend.', '{"topic":"work_entrepreneurship","voice":"adult_female","duration_estimate":20}'::jsonb),
('4681bac3-0c70-41b9-ba20-3a4626f5b72a'::uuid, 'cefr', 'assessment_listening', 'a1', 'al-a1-06', '/listening/assessment/a1/al-a1-06.mp3', NULL, NULL, 'How many bedrooms are in the house?', '[{"key":"A","label":"One"},{"key":"B","label":"Three"},{"key":"C","label":"Two"},{"key":"D","label":"Four"}]'::jsonb, 'C', 'The speaker says "two bedrooms."', 'generated_then_curated', '2026-05-18T17:30:16.407296+00:00'::timestamptz, 'listening', 'enabled', 'I live in a small house. There are four rooms: a kitchen, a living room, and two bedrooms. We have a garden with flowers.', '{"topic":"home","voice":"child_female","duration_estimate":10}'::jsonb),
('514136de-2036-4e19-b6b2-78544986a09e'::uuid, 'cambridge', 'fce_listening_part1', 'b2', 'fl-p1-03', '/fce-listening-part1/fl-p1-03.mp3', NULL, NULL, 'What is the speaker''s view of the painting?', '[{"key":"A","label":"Its apparent emptiness is a deliberate and effective artistic choice"},{"key":"B","label":"The artist made a technical error that paradoxically works"},{"key":"C","label":"It achieves its impact despite being genuinely unfinished"}]'::jsonb, 'A', 'The speaker argues the empty space is intentional and that critics confusing absence with incompleteness are wrong.', 'generated_then_curated', '2026-05-19T14:11:58.471575+00:00'::timestamptz, 'listening', 'enabled', 'When I look at this painting, I''m immediately drawn to what the artist chose not to include. The left third of the canvas is almost empty — just a wash of cool grey. In any other composition that would read as a mistake, a failure of balance. But here it amplifies the weight of the single figure on the right. She stands completely still, and yet you feel the accumulated tension of whatever preceded this moment. The restraint is what makes it devastating. Some critics have called this work unfinished. I think they''re confusing absence with incompleteness.', '{"topic":"art_critique","voice":"adult_female","question_focus":"opinion","estimated_seconds":46}'::jsonb),
('56bfc418-d548-4460-ac97-60cfaa36eb46'::uuid, 'cefr', 'assessment_listening', 'a1', 'al-a1-05', '/listening/assessment/a1/al-a1-05.mp3', NULL, NULL, 'What day is it?', '[{"key":"A","label":"Tuesday"},{"key":"B","label":"Sunday"},{"key":"C","label":"Friday"},{"key":"D","label":"Monday"}]'::jsonb, 'D', 'The speaker says "It is Monday."', 'generated_then_curated', '2026-05-18T17:30:16.407296+00:00'::timestamptz, 'listening', 'enabled', 'It is Monday. The weather is sunny today. I want to play football with my friends in the park after school.', '{"topic":"days_weather","voice":"child_male","duration_estimate":10}'::jsonb),
('58883da2-fff0-4e28-a19f-25ccff6f0a09'::uuid, 'cefr', 'assessment_reading', 'b2', 'ar-b2-08', NULL, 'The novelist remarked in her interview that she never writes with a reader in mind. "The moment I imagine an audience," she explained, "I start censoring myself. The draft becomes self-conscious, performative — it loses the rawness that, I believe, is the only honest thing writing can offer." Her publisher, diplomatically, declined to comment.', NULL, 'What can be inferred about the novelist''s publisher?', '[{"key":"A","label":"The publisher agrees with her approach"},{"key":"B","label":"The publisher is also a novelist"},{"key":"C","label":"The publisher may have reservations about her view"},{"key":"D","label":"The publisher wrote the article about her"}]'::jsonb, 'C', 'The publisher "diplomatically declined to comment" — the word "diplomatically" implies they have reservations but chose not to say so.', 'generated_then_curated', '2026-05-18T18:31:46.992101+00:00'::timestamptz, 'reading', 'enabled', NULL, '{"genre":"interview_extract","topic":"literature_creativity","estimated_seconds":65}'::jsonb),
('58f750d8-33f8-44c0-9217-56759eb2780a'::uuid, 'cefr', 'assessment_listening', 'b1', 'al-b1-02', '/listening/assessment/b1/al-b1-02.mp3', NULL, NULL, 'What do Sarah and Tom decide to do?', '[{"key":"A","label":"Travel abroad"},{"key":"B","label":"Stay at home"},{"key":"C","label":"Take a short trip to Scotland"},{"key":"D","label":"Buy a flat immediately"}]'::jsonb, 'C', 'They "agree to take a short trip to Scotland instead."', 'generated_then_curated', '2026-05-18T17:30:16.407296+00:00'::timestamptz, 'listening', 'enabled', 'Sarah and Tom are discussing their plans for the summer. Sarah wants to go travelling abroad, but Tom thinks they should save money this year because they''re planning to buy a flat next spring. In the end, they agree to take a short trip to Scotland instead.', '{"topic":"plans_decisions","voice":"adult_mixed","duration_estimate":18}'::jsonb),
('5c1258a6-6b5b-4fd4-a075-fc932500cc47'::uuid, 'cefr', 'assessment_reading', 'b1', 'ar-b1-04', NULL, 'Many teenagers report feeling stressed about their future careers. A recent survey found that 68% of 15-year-olds worry about whether they will find a good job. Career advisers suggest that young people should explore their interests rather than focus on salary, as job satisfaction is closely linked to long-term wellbeing.', NULL, 'What do career advisers recommend?', '[{"key":"A","label":"Getting a high salary"},{"key":"B","label":"Focusing on maths and science"},{"key":"C","label":"Exploring personal interests"},{"key":"D","label":"Choosing a job early"}]'::jsonb, 'C', 'Advisers suggest "young people should explore their interests."', 'generated_then_curated', '2026-05-18T18:31:46.992101+00:00'::timestamptz, 'reading', 'enabled', NULL, '{"genre":"article","topic":"careers_future","estimated_seconds":50}'::jsonb),
('6d8e08f4-f4b9-4746-a648-91b587d54192'::uuid, 'cefr', 'assessment_listening', 'a1', 'al-a1-02', '/listening/assessment/a1/al-a1-02.mp3', NULL, NULL, 'What colour is the dog?', '[{"key":"A","label":"Black"},{"key":"B","label":"White"},{"key":"C","label":"Brown"},{"key":"D","label":"Yellow"}]'::jsonb, 'C', 'The speaker says "The dog is brown."', 'generated_then_curated', '2026-05-18T17:30:16.407296+00:00'::timestamptz, 'listening', 'enabled', 'Look at the picture. It is a dog. The dog is brown. It is big. It is playing in the garden.', '{"topic":"animals_colours","voice":"child_female","duration_estimate":9}'::jsonb),
('6efa7047-016c-499e-a61b-27a72823e851'::uuid, 'cefr', 'assessment_listening', 'a2', 'al-a2-05', '/listening/assessment/a2/al-a2-05.mp3', NULL, NULL, 'When can you collect the books?', '[{"key":"A","label":"Seven days a week"},{"key":"B","label":"Monday to Friday"},{"key":"C","label":"Weekends only"},{"key":"D","label":"Monday to Saturday"}]'::jsonb, 'B', 'The message says "Monday to Friday."', 'generated_then_curated', '2026-05-18T17:30:16.407296+00:00'::timestamptz, 'listening', 'enabled', 'This is a message from Westfield Library. The books you ordered have arrived. You can collect them from Monday to Friday between nine and six. Please bring your library card.', '{"topic":"library_messages","voice":"adult_female","duration_estimate":13}'::jsonb),
('6f9ef241-30a0-4a85-be78-45d1bbea20d5'::uuid, 'cefr', 'assessment_listening', 'b1', 'al-b1-06', '/listening/assessment/b1/al-b1-06.mp3', NULL, NULL, 'According to the study, what is one cause of poor sleep in teenagers?', '[{"key":"A","label":"Eating too late"},{"key":"B","label":"Loud music"},{"key":"C","label":"Screen use before bedtime"},{"key":"D","label":"Exercising at night"}]'::jsonb, 'C', 'The study notes "screen use before bedtime is one of the main causes."', 'generated_then_curated', '2026-05-18T17:30:16.407296+00:00'::timestamptz, 'listening', 'enabled', 'A radio presenter is talking about a new study on sleep. Scientists found that teenagers who sleep less than eight hours a night perform significantly worse in tests than those who sleep eight or more hours. The study also noted that screen use before bedtime is one of the main causes of poor sleep.', '{"topic":"health_science","voice":"adult_male","duration_estimate":19}'::jsonb),
('6fffedc8-338d-4dd4-b124-55b12f1e47e0'::uuid, 'cambridge', 'fce_listening_part1', 'b2', 'fl-p1-02', '/fce-listening-part1/fl-p1-02.mp3', NULL, NULL, 'What is the speaker most worried about regarding coral reefs?', '[{"key":"A","label":"The absolute rise in ocean temperature"},{"key":"B","label":"The lack of time between bleaching events for recovery"},{"key":"C","label":"The declining number of scientists monitoring the reefs"}]'::jsonb, 'B', 'The speaker states that shortened recovery windows between bleaching events are the main concern, not the individual events themselves.', 'generated_then_curated', '2026-05-19T14:11:58.471575+00:00'::timestamptz, 'listening', 'enabled', 'The data collected over the last decade paints a troubling picture for coastal ecosystems. Ocean temperatures have risen by an average of one point two degrees Celsius in the regions we study, which sounds modest until you consider the cascading effects. Coral bleaching events that once occurred roughly every thirty years now happen every five to seven. What concerns me most is not the bleaching itself — corals can recover from individual events — but the shortened recovery windows. The intervals are now so brief that the systems simply cannot rebuild before the next thermal stress event arrives.', '{"topic":"environmental_issues","voice":"adult_male","question_focus":"opinion","estimated_seconds":48}'::jsonb),
('74d12724-8f0e-447c-bc2a-4d5213146d28'::uuid, 'cefr', 'assessment_reading', 'b1', 'ar-b1-06', NULL, 'Kieran had always dreamed of travelling, but money was a constant obstacle. When he saw an advert for a paid work-exchange programme in Japan, he applied immediately. Six months later, he was teaching English in a small mountain town, slowly building the savings that would fund his next adventure.', NULL, 'What is suggested about Kieran''s financial situation?', '[{"key":"A","label":"He is very wealthy"},{"key":"B","label":"He cannot afford to travel without working"},{"key":"C","label":"He has a well-paid job at home"},{"key":"D","label":"His family pays for his trips"}]'::jsonb, 'B', 'The text says "money was a constant obstacle," implying he needs to earn money to travel.', 'generated_then_curated', '2026-05-18T18:31:46.992101+00:00'::timestamptz, 'reading', 'enabled', NULL, '{"genre":"narrative","topic":"travel_work","estimated_seconds":50}'::jsonb),
('75f30a0f-c506-4dce-be67-5b822355cfb5'::uuid, 'cefr', 'assessment_reading', 'a1', 'ar-a1-02', NULL, 'Library notice: The library is open Monday to Friday from 9 am to 5 pm. It is closed on Saturday and Sunday. Children under 12 need a parent with them.', NULL, 'When is the library closed?', '[{"key":"A","label":"Monday"},{"key":"B","label":"Friday"},{"key":"C","label":"Saturday and Sunday"},{"key":"D","label":"Every morning"}]'::jsonb, 'C', 'The notice says "It is closed on Saturday and Sunday."', 'generated_then_curated', '2026-05-18T18:31:46.992101+00:00'::timestamptz, 'reading', 'enabled', NULL, '{"genre":"notice","topic":"public_signs","estimated_seconds":30}'::jsonb),
('82c706d7-678b-4658-b7c1-5b696e278dfe'::uuid, 'cefr', 'assessment_listening', 'b2', 'al-b2-08', '/listening/assessment/b2/al-b2-08.mp3', NULL, NULL, 'What misconception does the neuroscientist address?', '[{"key":"A","label":"That neuroplasticity only exists in children"},{"key":"B","label":"That adults learn new skills as easily as children"},{"key":"C","label":"That the brain stops changing after age thirty"},{"key":"D","label":"That intelligence is fixed at birth"}]'::jsonb, 'B', 'She cautions against "the misconception that this means adults can learn any skill as easily as children."', 'generated_then_curated', '2026-05-18T17:30:16.407296+00:00'::timestamptz, 'listening', 'enabled', 'The neuroscientist being interviewed explains that the human brain is remarkably adaptable — a property known as neuroplasticity. However, she cautions against the popular misconception that this means adults can learn any skill as easily as children can. While the brain does retain plasticity throughout life, the rate of change slows considerably after adolescence.', '{"topic":"neuroscience_interview","voice":"adult_female","duration_estimate":23}'::jsonb),
('852776e2-63ff-4d88-ba6e-3f2ece8fd7db'::uuid, 'cambridge', 'fce_listening_part1', 'b2', 'fl-p1-09', '/fce-listening-part1/fl-p1-09.mp3', NULL, NULL, 'According to the speaker, what is the most damaging effect of social media on democracy?', '[{"key":"A","label":"The rapid spread of factually incorrect political information"},{"key":"B","label":"The way algorithmic design undermines the conditions needed for political dialogue"},{"key":"C","label":"The decline of long-form journalism in favour of short emotional content"}]'::jsonb, 'B', 'The speaker explicitly frames misinformation as secondary to the structural distortion of what people think politics is for, driven by engagement-optimised algorithms.', 'generated_then_curated', '2026-05-19T14:11:58.471575+00:00'::timestamptz, 'listening', 'enabled', 'Social media has fundamentally altered the way we form political opinions, and not simply because of misinformation. The deeper effect is structural. Algorithms optimise for engagement, and engagement correlates with emotional arousal — particularly outrage and fear. Over time this doesn''t just distort what people believe; it distorts what they think politics is for. When every issue arrives pre-packaged with a moral adversary, deliberation starts to feel naive. People begin to see compromise not as a democratic virtue but as a form of betrayal. That''s the real corrosion: not specific false claims, but the erosion of the cognitive and emotional conditions that make democratic discourse possible.', '{"topic":"social_commentary","voice":"teenager_female","question_focus":"gist","estimated_seconds":52}'::jsonb),
('85416cd1-76ce-40e4-881a-1ecaae2d085e'::uuid, 'cefr', 'assessment_reading', 'b1', 'ar-b1-07', NULL, 'Research shows that students who sleep fewer than eight hours a night are likely to perform worse in tests and have difficulty concentrating in class. Despite this, many teenagers go to bed after midnight due to homework, social media, or part-time jobs. Experts recommend setting a regular sleep schedule as the most effective solution.', NULL, 'According to the text, what causes many teenagers to sleep late?', '[{"key":"A","label":"They enjoy night-time activities"},{"key":"B","label":"Their parents allow it"},{"key":"C","label":"Homework, social media or part-time jobs"},{"key":"D","label":"School starts too early"}]'::jsonb, 'C', 'The text says teenagers go to bed late "due to homework, social media, or part-time jobs."', 'generated_then_curated', '2026-05-18T18:31:46.992101+00:00'::timestamptz, 'reading', 'enabled', NULL, '{"genre":"article","topic":"health_sleep","estimated_seconds":50}'::jsonb),
('8a4e6135-be24-4e13-b894-0dd9b9fcc260'::uuid, 'cefr', 'assessment_reading', 'a2', 'ar-a2-07', NULL, 'My cousin Leo moved to our city last month. He goes to my school now. At first he was nervous because he didn''t know anyone, but now he has made several new friends and really enjoys his classes.', NULL, 'How does Leo feel now?', '[{"key":"A","label":"Nervous"},{"key":"B","label":"Bored"},{"key":"C","label":"Happy"},{"key":"D","label":"Tired"}]'::jsonb, 'C', 'The text says Leo "really enjoys his classes" and has made new friends — he feels happy.', 'generated_then_curated', '2026-05-18T18:31:46.992101+00:00'::timestamptz, 'reading', 'enabled', NULL, '{"genre":"personal_narrative","topic":"school_social","estimated_seconds":40}'::jsonb),
('8b51e33e-ea82-4d8f-bbe3-64455f86da26'::uuid, 'cefr', 'assessment_reading', 'a2', 'ar-a2-05', NULL, 'Lost cat! Our grey and white cat, Misty, went missing on Tuesday evening near Pine Avenue. She is three years old and very friendly. If you see her, please call 07700 900123. Reward offered.', NULL, 'What colour is Misty?', '[{"key":"A","label":"Black and white"},{"key":"B","label":"Orange"},{"key":"C","label":"Grey and white"},{"key":"D","label":"Brown"}]'::jsonb, 'C', 'The notice says "Our grey and white cat, Misty."', 'generated_then_curated', '2026-05-18T18:31:46.992101+00:00'::timestamptz, 'reading', 'enabled', NULL, '{"genre":"notice","topic":"community_notices","estimated_seconds":35}'::jsonb),
('93a45df3-1d17-4f7e-9f99-03c59930c6f4'::uuid, 'cefr', 'assessment_listening', 'b1', 'al-b1-04', '/listening/assessment/b1/al-b1-04.mp3', NULL, NULL, 'Why has the gate changed?', '[{"key":"A","label":"Security reasons"},{"key":"B","label":"A technical issue"},{"key":"C","label":"The plane arrived late"},{"key":"D","label":"Overcrowding at gate 14"}]'::jsonb, 'B', 'The announcement states "due to a technical issue."', 'generated_then_curated', '2026-05-18T17:30:16.407296+00:00'::timestamptz, 'listening', 'enabled', 'Attention all passengers on flight BA 472 to Barcelona. Due to a technical issue, your departure has been moved from gate fourteen to gate twenty-two. Boarding will begin in thirty minutes. We apologise for this change and thank you for your patience.', '{"topic":"travel_announcements","voice":"adult_female","duration_estimate":17}'::jsonb),
('97e308f4-d2c3-4480-b1ae-ad65ea98d09f'::uuid, 'cambridge', 'fce_listening_part1', 'b2', 'fl-p1-04', '/fce-listening-part1/fl-p1-04.mp3', NULL, NULL, 'What is the speaker''s main point about AI in recruitment?', '[{"key":"A","label":"Algorithms should be banned from hiring decisions entirely"},{"key":"B","label":"Claiming AI tools are neutral ignores how they inherit historical biases"},{"key":"C","label":"Companies deliberately train systems to discriminate against minorities"}]'::jsonb, 'B', 'The speaker argues that neutrality is a category error because the training data itself encodes historical bias — not that companies act with deliberate discriminatory intent.', 'generated_then_curated', '2026-05-19T14:11:58.471575+00:00'::timestamptz, 'listening', 'enabled', 'There''s a question I keep coming back to when I think about algorithmic decision-making in hiring: who is responsible when the system is wrong? Companies typically argue that the algorithm is a neutral tool. But neutrality is impossible when the training data reflects historical hiring patterns that systematically excluded certain groups. The algorithm learns to replicate those patterns precisely because they look like successful outcomes in the data. Calling that neutrality is a category error. The real ethical question is not whether to use AI in hiring, but who bears accountability when it perpetuates injustice.', '{"topic":"technology_ethics","voice":"adult_male","question_focus":"gist","estimated_seconds":47}'::jsonb),
('98226ba0-8e01-423a-a050-5561c646b2cf'::uuid, 'cefr', 'assessment_reading', 'a1', 'ar-a1-04', NULL, 'Anna likes fruit. She eats an apple every day. Her favourite fruit is a mango. She does not like oranges.', NULL, 'What is Anna''s favourite fruit?', '[{"key":"A","label":"Apple"},{"key":"B","label":"Orange"},{"key":"C","label":"Banana"},{"key":"D","label":"Mango"}]'::jsonb, 'D', 'The text says "Her favourite fruit is a mango."', 'generated_then_curated', '2026-05-18T18:31:46.992101+00:00'::timestamptz, 'reading', 'enabled', NULL, '{"genre":"personal_description","topic":"food","estimated_seconds":25}'::jsonb),
('988c8b74-dfaa-4edf-a85e-b163c5c84d3c'::uuid, 'cefr', 'assessment_listening', 'a1', 'al-a1-03', '/listening/assessment/a1/al-a1-03.mp3', NULL, NULL, 'What time does school start?', '[{"key":"A","label":"Eight o''clock"},{"key":"B","label":"Nine o''clock"},{"key":"C","label":"Ten o''clock"},{"key":"D","label":"Seven o''clock"}]'::jsonb, 'B', 'The speaker says "My school starts at nine o''clock."', 'generated_then_curated', '2026-05-18T17:30:16.407296+00:00'::timestamptz, 'listening', 'enabled', 'I go to school every day. My school starts at nine o''clock. I like drawing and music. My favourite food is pizza.', '{"topic":"school_routine","voice":"child_female","duration_estimate":10}'::jsonb),
('9978e100-d2fd-4c36-8b74-8e269cdd8716'::uuid, 'cefr', 'assessment_reading', 'b2', 'ar-b2-01', NULL, 'While many people assume that multitasking increases productivity, cognitive science tells a different story. Studies consistently show that switching rapidly between tasks reduces the quality of work and increases errors. The human brain, it turns out, is not designed to process multiple streams of complex information simultaneously. What we call "multitasking" is, in reality, rapid task-switching — and each switch comes at a cognitive cost.', NULL, 'What does the author suggest about multitasking?', '[{"key":"A","label":"It is only effective for simple tasks"},{"key":"B","label":"It genuinely improves productivity"},{"key":"C","label":"It is a myth that reduces work quality"},{"key":"D","label":"It is useful when tasks are similar"}]'::jsonb, 'C', 'The text argues multitasking "reduces the quality of work" and is actually rapid task-switching — a myth.', 'generated_then_curated', '2026-05-18T18:31:46.992101+00:00'::timestamptz, 'reading', 'enabled', NULL, '{"genre":"academic_article","topic":"psychology_cognition","estimated_seconds":60}'::jsonb),
('9c733bae-8410-4f10-8a2f-aeba656a651f'::uuid, 'cambridge', 'pet_listening_part2', 'b1', 'pl-p2-03', '/pet-listening-part2/pl-p2-03.mp3', NULL, NULL, 'What did the researchers find about breakfast?', '[{"key":"A","label":"Students who ate a large breakfast did best"},{"key":"B","label":"Skipping breakfast had no effect on test scores"},{"key":"C","label":"Even a small breakfast improved morning performance"},{"key":"D","label":"Benefits were only seen in afternoon lessons"}]'::jsonb, 'C', 'The report says even a small snack was enough, so the size of breakfast did not matter — just eating something helped.', 'generated_then_curated', '2026-05-19T13:52:11.261222+00:00'::timestamptz, 'listening', 'enabled', 'A new report published this week suggests that teenagers who eat breakfast regularly perform better in morning classes than those who skip it. Researchers followed five hundred students for six months. They found that students who had breakfast showed improved concentration and scored on average twelve percent higher in tests taken before midday. Interestingly, the type of breakfast didn''t seem to matter much — even a small snack was enough to make a difference.', '{"topic":"health_education","voice":"adult_male","estimated_seconds":23}'::jsonb),
('9d57d7b9-c745-4dbd-9f48-109e7110b685'::uuid, 'cambridge', 'pet_listening_part2', 'b1', 'pl-p2-04', '/pet-listening-part2/pl-p2-04.mp3', NULL, NULL, 'According to the speaker, what most improved their photography?', '[{"key":"A","label":"Buying a professional camera"},{"key":"B","label":"Watching online tutorials"},{"key":"C","label":"Practising alone every day"},{"key":"D","label":"Getting feedback from a photography club"}]'::jsonb, 'D', 'The speaker says joining a club and receiving honest critique helped far more than the new camera.', 'generated_then_curated', '2026-05-19T13:52:11.261222+00:00'::timestamptz, 'listening', 'enabled', 'I started learning photography three years ago, and the biggest lesson I''ve learned is that expensive equipment doesn''t automatically make better photos. I spent ages saving up for a professional camera, but when I finally got it I realised my compositions weren''t improving at all. It was only when I joined a photography club and got feedback from other members that things started to click. The community and honest critique helped far more than any piece of kit.', '{"topic":"hobbies","voice":"teenager_female","estimated_seconds":22}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  framework = EXCLUDED.framework,
  exam_part = EXCLUDED.exam_part,
  cefr_level = EXCLUDED.cefr_level,
  variant_id = EXCLUDED.variant_id,
  stimulus_audio_url = EXCLUDED.stimulus_audio_url,
  stimulus_text = EXCLUDED.stimulus_text,
  stimulus_image_url = EXCLUDED.stimulus_image_url,
  question = EXCLUDED.question,
  options = EXCLUDED.options,
  correct_key = EXCLUDED.correct_key,
  explanation = EXCLUDED.explanation,
  source = EXCLUDED.source,
  skill = EXCLUDED.skill,
  status = EXCLUDED.status,
  transcript = EXCLUDED.transcript,
  metadata = EXCLUDED.metadata;

INSERT INTO bob_closed_items (id, framework, exam_part, cefr_level, variant_id, stimulus_audio_url, stimulus_text, stimulus_image_url, question, options, correct_key, explanation, source, created_at, skill, status, transcript, metadata)
VALUES
('9f4f9684-9a60-46ec-9f20-642b9ebe9930'::uuid, 'cefr', 'assessment_listening', 'a2', 'al-a2-03', '/listening/assessment/a2/al-a2-03.mp3', NULL, NULL, 'What day is James''s appointment?', '[{"key":"A","label":"Tuesday"},{"key":"B","label":"Wednesday"},{"key":"C","label":"Thursday"},{"key":"D","label":"Friday"}]'::jsonb, 'C', 'The message says "on Thursday at four fifteen."', 'generated_then_curated', '2026-05-18T17:30:16.407296+00:00'::timestamptz, 'listening', 'enabled', 'Hi, this is a message for James. Your dentist appointment is on Thursday at four fifteen. Please call us if you need to change the time. The number is 0800 234 567.', '{"topic":"appointments","voice":"adult_male","duration_estimate":13}'::jsonb),
('a1d9fa5a-b839-4d41-936f-20f833d64c68'::uuid, 'cefr', 'assessment_reading', 'a1', 'ar-a1-06', NULL, 'Dear Mum, I am having a great time at camp. We swim every afternoon. The food is good. I miss you. Love, Jake', NULL, 'What does Jake do every afternoon at camp?', '[{"key":"A","label":"Play football"},{"key":"B","label":"Swim"},{"key":"C","label":"Cook"},{"key":"D","label":"Sleep"}]'::jsonb, 'B', 'Jake writes "We swim every afternoon."', 'generated_then_curated', '2026-05-18T18:31:46.992101+00:00'::timestamptz, 'reading', 'enabled', NULL, '{"genre":"letter","topic":"holidays","estimated_seconds":30}'::jsonb),
('a26cde7c-6643-4f2b-a2f6-ba0d7e4d0d3a'::uuid, 'cefr', 'assessment_reading', 'b2', 'ar-b2-06', NULL, 'After three rounds of funding, the start-up had yet to turn a profit. Investors were growing impatient, and the CEO — aware that another missed quarter would likely trigger a board vote — decided to pivot the company''s strategy dramatically, targeting enterprise clients rather than the consumer market that had, so far, failed to materialise.', NULL, 'Why did the CEO change the company''s strategy?', '[{"key":"A","label":"The enterprise market was more fashionable"},{"key":"B","label":"Investors demanded a consumer focus"},{"key":"C","label":"She feared losing control of the company if results did not improve"},{"key":"D","label":"The original product was technically flawed"}]'::jsonb, 'C', 'The CEO knew "another missed quarter would likely trigger a board vote" — she acted to keep control.', 'generated_then_curated', '2026-05-18T18:31:46.992101+00:00'::timestamptz, 'reading', 'enabled', NULL, '{"genre":"narrative","topic":"business_startups","estimated_seconds":60}'::jsonb),
('a39a3ffa-610f-4f55-9399-c45d9c357892'::uuid, 'cefr', 'assessment_listening', 'a2', 'al-a2-07', '/listening/assessment/a2/al-a2-07.mp3', NULL, NULL, 'Which platform should passengers wait on?', '[{"key":"A","label":"Platform one"},{"key":"B","label":"Platform two"},{"key":"C","label":"Platform four"},{"key":"D","label":"Platform three"}]'::jsonb, 'D', 'The announcement says "wait on platform three."', 'generated_then_curated', '2026-05-18T17:30:16.407296+00:00'::timestamptz, 'listening', 'enabled', 'Train service update: the eleven forty-five to Manchester is delayed by approximately twenty minutes. Passengers are advised to wait on platform three. We apologise for any inconvenience.', '{"topic":"transport_announcements","voice":"adult_male","duration_estimate":13}'::jsonb),
('abc37045-0605-4926-8914-4cd916b845c8'::uuid, 'cefr', 'assessment_reading', 'a2', 'ar-a2-01', NULL, 'Maria is 13 years old and lives in Madrid. She loves reading and goes to the library every Saturday. Last week she borrowed a mystery novel. She read the whole book in two days because she found it very exciting.', NULL, 'Why did Maria finish the book so quickly?', '[{"key":"A","label":"The library closed"},{"key":"B","label":"Her friend wanted it"},{"key":"C","label":"She found it very exciting"},{"key":"D","label":"It was very short"}]'::jsonb, 'C', 'The text says she read it quickly "because she found it very exciting."', 'generated_then_curated', '2026-05-18T18:31:46.992101+00:00'::timestamptz, 'reading', 'enabled', NULL, '{"genre":"personal_description","topic":"hobbies_reading","estimated_seconds":40}'::jsonb),
('ac39da5f-30bf-4ac3-b91d-5ae26473b738'::uuid, 'cambridge', 'pet_listening_part2', 'b1', 'pl-p2-05', '/pet-listening-part2/pl-p2-05.mp3', NULL, NULL, 'Until what time will the food court be open this Sunday?', '[{"key":"A","label":"Five o''clock"},{"key":"B","label":"Six o''clock"},{"key":"C","label":"Six thirty"},{"key":"D","label":"Eight o''clock"}]'::jsonb, 'B', 'The announcement states the food court will remain open until six, one hour later than the shops.', 'generated_then_curated', '2026-05-19T13:52:11.261222+00:00'::timestamptz, 'listening', 'enabled', 'Attention, shoppers. Westgate Shopping Centre will be closing earlier than usual this Sunday due to a staff training day. Shops will close at five o''clock instead of the normal eight o''clock. The food court, however, will remain open until six. Car park exits will be available until six thirty. We apologise for any inconvenience and look forward to welcoming you back next week during normal hours.', '{"topic":"announcements","voice":"adult_female","estimated_seconds":19}'::jsonb),
('ae6ed91e-5ee3-45bf-8c11-1c936bb24fe5'::uuid, 'cefr', 'assessment_listening', 'a2', 'al-a2-06', '/listening/assessment/a2/al-a2-06.mp3', NULL, NULL, 'Who did Jake go on holiday with?', '[{"key":"A","label":"Friends"},{"key":"B","label":"His parents only"},{"key":"C","label":"His parents and sister"},{"key":"D","label":"His grandparents"}]'::jsonb, 'C', 'Jake says "with his parents and sister."', 'generated_then_curated', '2026-05-18T17:30:16.407296+00:00'::timestamptz, 'listening', 'enabled', 'Jake is talking about his holiday. He went to Portugal with his parents and sister. It was very hot — about thirty-five degrees. They swam in the sea every day and ate lots of seafood.', '{"topic":"holidays_travel","voice":"teenager_male","duration_estimate":14}'::jsonb),
('b2c3a99e-d99a-4625-82c0-ae888f3c8e1d'::uuid, 'cambridge', 'fce_listening_part1', 'b2', 'fl-p1-05', '/fce-listening-part1/fl-p1-05.mp3', NULL, NULL, 'How did the speaker feel during the first few days of the trip?', '[{"key":"A","label":"Overwhelmed and tempted to cut the trip short"},{"key":"B","label":"Excited despite finding the language barrier frustrating"},{"key":"C","label":"Disappointed that Japan did not match her expectations"}]'::jsonb, 'A', 'The speaker says she nearly booked an earlier flight home on the third day, indicating she was close to abandoning the trip.', 'generated_then_curated', '2026-05-19T14:11:58.471575+00:00'::timestamptz, 'listening', 'enabled', 'I''d done enough research on Japan before arriving to feel reasonably prepared. What I hadn''t anticipated was the physical exhaustion of navigating a city that operates on an entirely different logic — signage in unfamiliar scripts, social codes I kept misreading, the particular loneliness of being surrounded by millions of people none of whom need anything from you. By the third day I nearly booked an earlier flight home. What stopped me was a conversation with a local ceramics teacher who spotted me looking lost outside his studio. He invited me in, made tea, and spent two hours showing me traditional raku techniques. That moment reframed everything that followed.', '{"topic":"travel_experiences","voice":"adult_female","question_focus":"feeling","estimated_seconds":50}'::jsonb),
('b7c35146-249c-4465-9a2c-c48a61a982aa'::uuid, 'cambridge', 'pet_listening_part2', 'b1', 'pl-p2-08', '/pet-listening-part2/pl-p2-08.mp3', NULL, NULL, 'Why has the date of the summer fair changed?', '[{"key":"A","label":"The venue was not available on the original date"},{"key":"B","label":"Some key staff will be absent on the original date"},{"key":"C","label":"The school band was not ready to perform"},{"key":"D","label":"Not enough tickets had been sold"}]'::jsonb, 'B', 'The announcement explicitly states the change was because several key staff members will be away.', 'generated_then_curated', '2026-05-19T13:52:11.261222+00:00'::timestamptz, 'listening', 'enabled', 'The school is pleased to announce that the summer fair will be held on the fourteenth of June this year, a week later than originally planned. This change was made because several key staff members will be away on the previously scheduled date. All the usual activities will be included: games, a food stall, a raffle, and live music from the school band. Tickets are available from the school office from Monday.', '{"topic":"school_events","voice":"adult_female","estimated_seconds":21}'::jsonb),
('ba6c91af-e5fc-4280-a6ec-5c963456ef8e'::uuid, 'cefr', 'assessment_listening', 'b2', 'al-b2-06', '/listening/assessment/b2/al-b2-06.mp3', NULL, NULL, 'According to scientists, what are TWO reasons deforestation has continued?', '[{"key":"A","label":"Climate change and tourism"},{"key":"B","label":"Demand for agricultural land and governance failures"},{"key":"C","label":"Population growth and lack of education"},{"key":"D","label":"Industrial pollution and mining"}]'::jsonb, 'B', 'Scientists cite "demand for agricultural land" and "governance failures."', 'generated_then_curated', '2026-05-18T17:30:16.407296+00:00'::timestamptz, 'listening', 'enabled', 'The documentary narrator explains that despite decades of international agreements, deforestation in tropical regions has accelerated rather than slowed. Scientists attribute this partly to the increased demand for agricultural land, but also to governance failures and insufficient funding for conservation programmes in developing nations.', '{"topic":"environment_documentary","voice":"adult_male","duration_estimate":22}'::jsonb),
('c0ab2297-d484-421a-a625-0971bc8974e5'::uuid, 'cefr', 'assessment_listening', 'a1', 'al-a1-04', '/listening/assessment/a1/al-a1-04.mp3', NULL, NULL, 'How many brothers does the speaker have?', '[{"key":"A","label":"Two"},{"key":"B","label":"Three"},{"key":"C","label":"One"},{"key":"D","label":"None"}]'::jsonb, 'C', 'The speaker says "I have one brother."', 'generated_then_curated', '2026-05-18T17:30:16.407296+00:00'::timestamptz, 'listening', 'enabled', 'This is my family. My mum is tall. My dad has got glasses. I have one brother. His name is Jack.', '{"topic":"family","voice":"child_male","duration_estimate":9}'::jsonb),
('c29ccf4b-a7ba-4b19-a574-ebc7f32b93f7'::uuid, 'cefr', 'assessment_reading', 'b1', 'ar-b1-01', NULL, 'Although Fatima had studied hard for her chemistry exam, she felt uncertain as she walked into the hall. The questions were harder than expected, and she spent too long on the first section. By the time she reached the last part, she only had ten minutes left. She handed in her paper feeling disappointed.', NULL, 'Why was Fatima disappointed?', '[{"key":"A","label":"She forgot to study"},{"key":"B","label":"She ran out of time"},{"key":"C","label":"The exam was cancelled"},{"key":"D","label":"Her teacher was not there"}]'::jsonb, 'B', 'Fatima "spent too long on the first section" and had only ten minutes for the last part — she ran out of time.', 'generated_then_curated', '2026-05-18T18:31:46.992101+00:00'::timestamptz, 'reading', 'enabled', NULL, '{"genre":"narrative","topic":"school_exams","estimated_seconds":50}'::jsonb),
('c34f2539-bb9b-4f2d-8ba1-1b7152f59315'::uuid, 'cefr', 'assessment_reading', 'a1', 'ar-a1-05', NULL, 'SCHOOL CAFÉ — Open: 12:00–14:00 — Hot meals: £2.50 — Sandwiches: £1.20 — Drinks: 50p — No food outside the café, please.', NULL, 'How much does a hot meal cost?', '[{"key":"A","label":"50p"},{"key":"B","label":"£1.20"},{"key":"C","label":"£2.50"},{"key":"D","label":"£3.00"}]'::jsonb, 'C', 'The sign says "Hot meals: £2.50."', 'generated_then_curated', '2026-05-18T18:31:46.992101+00:00'::timestamptz, 'reading', 'enabled', NULL, '{"genre":"sign","topic":"school_life","estimated_seconds":25}'::jsonb),
('c4042430-78f8-4034-b2bd-32fcd2f7da25'::uuid, 'cefr', 'assessment_listening', 'b1', 'al-b1-01', '/listening/assessment/b1/al-b1-01.mp3', NULL, NULL, 'What is Dr Moore''s area of research?', '[{"key":"A","label":"Climate change"},{"key":"B","label":"Ocean pollution"},{"key":"C","label":"Marine biology"},{"key":"D","label":"Recycling technology"}]'::jsonb, 'B', 'The introduction says she has "spent the last ten years studying ocean pollution."', 'generated_then_curated', '2026-05-18T17:30:16.407296+00:00'::timestamptz, 'listening', 'enabled', 'Good afternoon, and welcome to today''s science programme. Our guest, Dr Helena Moore, has spent the last ten years studying ocean pollution. Today she''ll be talking about how microplastics affect fish populations and what individuals can do to help reduce the problem.', '{"topic":"science_environment","voice":"adult_female","duration_estimate":20}'::jsonb),
('cafc529e-9782-4e9c-b0bb-79c11229d71c'::uuid, 'cefr', 'assessment_reading', 'b1', 'ar-b1-08', NULL, 'Dear Mr Collins, I am writing to apply for the part-time shop assistant position advertised on your website. I am 17 years old and currently studying for my GCSEs. I have previous experience working in my uncle''s bakery every Saturday and I am available on weekends. I look forward to hearing from you. Yours sincerely, Priya Shah', NULL, 'What relevant experience does Priya mention?', '[{"key":"A","label":"Working in a school canteen"},{"key":"B","label":"Studying business at college"},{"key":"C","label":"Working in her uncle''s bakery"},{"key":"D","label":"Helping in a clothes shop"}]'::jsonb, 'C', 'Priya says "I have previous experience working in my uncle''s bakery."', 'generated_then_curated', '2026-05-18T18:31:46.992101+00:00'::timestamptz, 'reading', 'enabled', NULL, '{"genre":"formal_letter","topic":"job_applications","estimated_seconds":50}'::jsonb),
('d262e10c-72af-4726-a770-15ab75315f28'::uuid, 'toefl', 'listen_choose_response', 'b1', 'lcr-q1', '/listening/toefl/question-response/Listening1_Question Response_Question1.ogg', NULL, NULL, 'Choose the best response.', '[{"key":"A","label":"No, I was at the library yesterday."},{"key":"B","label":"Yes, I enjoy going to the library."},{"key":"C","label":"The library is closed on Sundays."},{"key":"D","label":"I returned the books last week."}]'::jsonb, 'A', 'Listening Module 1, Q1. Correct answer verified against official TOEFL Practice Test 1 answer key.', 'official', '2026-05-16T16:48:27.475087+00:00'::timestamptz, 'listening', 'enabled', NULL, NULL),
('d31961f7-6b59-479c-a9b9-af6ec5ac0d31'::uuid, 'cambridge', 'fce_listening_part1', 'b2', 'fl-p1-10', '/fce-listening-part1/fl-p1-10.mp3', NULL, NULL, 'What is the speaker''s view on rest and creative work?', '[{"key":"A","label":"Rest is a reward for high performance rather than a contributor to it"},{"key":"B","label":"Genuine cognitive disengagement is essential to creative output"},{"key":"C","label":"Creative professionals naturally find it harder to switch off than others"}]'::jsonb, 'B', 'The speaker argues that true rest — not performative busyness — enables the cognitive processes that produce original thinking.', 'generated_then_curated', '2026-05-19T14:11:58.471575+00:00'::timestamptz, 'listening', 'enabled', 'The assumption that productivity and wellbeing are in tension is one I''d push back on quite firmly. In my experience managing creative teams, the periods of highest output almost always follow periods of genuine rest — not the performative busyness people mistake for rest, scrolling through their phones, but actual cognitive disengagement. The neuroscience supports this: the default mode network, which is active during mind-wandering and daydreaming, plays a crucial role in consolidating learning and generating novel connections. The most counterproductive thing you can do with a creative team is keep them permanently stimulated. You starve the very process that produces original thinking.', '{"topic":"opinion_pieces","voice":"adult_male","question_focus":"opinion","estimated_seconds":50}'::jsonb),
('d786a1fb-7b08-40fb-a2ec-52a92e240c4e'::uuid, 'cefr', 'assessment_listening', 'b2', 'al-b2-07', '/listening/assessment/b2/al-b2-07.mp3', NULL, NULL, 'What is a key limitation of the AI plagiarism tool?', '[{"key":"A","label":"It is too slow to be useful"},{"key":"B","label":"It cannot detect copied passages"},{"key":"C","label":"It produces false positives with paraphrased content"},{"key":"D","label":"It is only available in English"}]'::jsonb, 'C', 'It "struggles with paraphrased content" and generates "false positives."', 'generated_then_curated', '2026-05-18T17:30:16.407296+00:00'::timestamptz, 'listening', 'enabled', 'A tech journalist is reviewing an artificial intelligence tool designed to detect plagiarism in academic writing. She notes that while the tool achieves high accuracy in identifying copied passages, it struggles with paraphrased content and has been criticised for generating false positives that unfairly penalise students.', '{"topic":"technology_education","voice":"adult_female","duration_estimate":22}'::jsonb),
('d78ffe24-a557-4050-baa3-088f11fb4cb2'::uuid, 'cefr', 'assessment_reading', 'a2', 'ar-a2-03', NULL, 'Hi Carla, I''m writing to invite you to my birthday party! It''s on Saturday 15th June at my house, starting at 3 pm. Please bring your swimming costume because we''ll use the garden pool. Hope you can come! — Lily', NULL, 'What should Carla bring to the party?', '[{"key":"A","label":"A cake"},{"key":"B","label":"A swimming costume"},{"key":"C","label":"A towel"},{"key":"D","label":"A present"}]'::jsonb, 'B', 'Lily says "Please bring your swimming costume."', 'generated_then_curated', '2026-05-18T18:31:46.992101+00:00'::timestamptz, 'reading', 'enabled', NULL, '{"genre":"email","topic":"social_invitations","estimated_seconds":35}'::jsonb),
('d8cce90c-45d2-479b-9233-4eddb80e3a52'::uuid, 'cambridge', 'pet_listening_part2', 'b1', 'pl-p2-07', '/pet-listening-part2/pl-p2-07.mp3', NULL, NULL, 'What is the speaker''s main problem?', '[{"key":"A","label":"She is failing her science subjects"},{"key":"B","label":"She cannot find a careers advisor"},{"key":"C","label":"She is unsure which career path to choose"},{"key":"D","label":"Her parents want her to study journalism"}]'::jsonb, 'C', 'The speaker is torn between her parents'' preference for medicine and her own interest in languages and writing, and has not yet decided.', 'generated_then_curated', '2026-05-19T13:52:11.261222+00:00'::timestamptz, 'listening', 'enabled', 'My parents think I should study medicine because there are always jobs, but honestly I find the sciences really hard. I''ve always been much better at languages and I love writing. My school careers advisor suggested journalism, which sounds exciting, but my mum says the industry is too unstable. I don''t know what to decide. I think I need more time to figure out what really motivates me before I commit to anything.', '{"topic":"work_career","voice":"teenager_female","estimated_seconds":22}'::jsonb),
('da4f9e5f-b52c-4750-802e-8d392d646bb6'::uuid, 'cefr', 'assessment_reading', 'b2', 'ar-b2-03', NULL, 'Dear Editor, I am writing in response to last week''s editorial, which argued that social media has been unambiguously harmful for young people. While I share the concern about screen time, I believe the picture is more nuanced. For marginalised teenagers — those who are isolated in their communities due to geography, disability or identity — online spaces can provide a vital sense of belonging. To condemn these platforms outright seems to ignore this reality.', NULL, 'What is the writer''s main point?', '[{"key":"A","label":"Social media is always beneficial for teenagers"},{"key":"B","label":"The negative effects of social media are exaggerated"},{"key":"C","label":"The impact of social media depends on the individual''s situation"},{"key":"D","label":"Teenagers should use social media less"}]'::jsonb, 'C', 'The writer argues the picture is "nuanced" and that for some marginalised teens, social media provides belonging — the impact depends on context.', 'generated_then_curated', '2026-05-18T18:31:46.992101+00:00'::timestamptz, 'reading', 'enabled', NULL, '{"genre":"letter_to_editor","topic":"social_media","estimated_seconds":65}'::jsonb),
('e4e27f29-0465-4529-b076-89b197bbb143'::uuid, 'cefr', 'assessment_reading', 'a2', 'ar-a2-08', NULL, 'FOR SALE: Mountain bike. Good condition. Used for one year. Suitable for ages 12–16. Price: £80 (was £150). Collection only. Call Dan on 07700 555321.', NULL, 'Why is the price reduced?', '[{"key":"A","label":"The bike is broken"},{"key":"B","label":"Dan needs the money quickly"},{"key":"C","label":"The advert does not say"},{"key":"D","label":"The bike is too small"}]'::jsonb, 'C', 'The advert gives no reason for the reduction — the text does not say.', 'generated_then_curated', '2026-05-18T18:31:46.992101+00:00'::timestamptz, 'reading', 'enabled', NULL, '{"genre":"advert","topic":"buying_selling","estimated_seconds":35}'::jsonb),
('e8aa9b99-7f06-4f37-9d18-0cc84f20eb74'::uuid, 'cefr', 'assessment_reading', 'a1', 'ar-a1-08', NULL, 'Today is Monday. School starts at 8:30. After school I go to football practice. It finishes at 5 o''clock. Then I do my homework.', NULL, 'What does the writer do after football practice?', '[{"key":"A","label":"Go to school"},{"key":"B","label":"Have dinner"},{"key":"C","label":"Do homework"},{"key":"D","label":"Watch TV"}]'::jsonb, 'C', 'The text says "Then I do my homework."', 'generated_then_curated', '2026-05-18T18:31:46.992101+00:00'::timestamptz, 'reading', 'enabled', NULL, '{"genre":"diary","topic":"daily_routine","estimated_seconds":30}'::jsonb),
('e9853b45-51bb-4b11-89bc-50a9f6dc0b60'::uuid, 'cefr', 'assessment_listening', 'b1', 'al-b1-05', '/listening/assessment/b1/al-b1-05.mp3', NULL, NULL, 'What is the new essay deadline?', '[{"key":"A","label":"Friday"},{"key":"B","label":"The following Monday"},{"key":"C","label":"Wednesday"},{"key":"D","label":"The following Friday"}]'::jsonb, 'B', 'The professor says "extended to the following Monday."', 'generated_then_curated', '2026-05-18T17:30:16.407296+00:00'::timestamptz, 'listening', 'enabled', 'A student is asking her professor about the essay deadline. The professor explains that the original deadline of Friday has been extended to the following Monday because several students have been ill. However, anyone who submits by Friday will still get their work back sooner.', '{"topic":"university_academic","voice":"adult_mixed","duration_estimate":18}'::jsonb),
('f11c210c-826b-4c3f-8b4e-84a765498b71'::uuid, 'cefr', 'assessment_listening', 'a2', 'al-a2-01', '/listening/assessment/a2/al-a2-01.mp3', NULL, NULL, 'What time is the special event?', '[{"key":"A","label":"Two o''clock"},{"key":"B","label":"Half past two"},{"key":"C","label":"Three o''clock"},{"key":"D","label":"Half past three"}]'::jsonb, 'B', 'The announcement says "at two thirty in the afternoon."', 'generated_then_curated', '2026-05-18T17:30:16.407296+00:00'::timestamptz, 'listening', 'enabled', 'Good morning! Welcome to Green Park Zoo. Today we have a special event at two thirty in the afternoon. You can feed the penguins near the lake. Children under twelve must be with an adult.', '{"topic":"announcements","voice":"adult_female","duration_estimate":15}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  framework = EXCLUDED.framework,
  exam_part = EXCLUDED.exam_part,
  cefr_level = EXCLUDED.cefr_level,
  variant_id = EXCLUDED.variant_id,
  stimulus_audio_url = EXCLUDED.stimulus_audio_url,
  stimulus_text = EXCLUDED.stimulus_text,
  stimulus_image_url = EXCLUDED.stimulus_image_url,
  question = EXCLUDED.question,
  options = EXCLUDED.options,
  correct_key = EXCLUDED.correct_key,
  explanation = EXCLUDED.explanation,
  source = EXCLUDED.source,
  skill = EXCLUDED.skill,
  status = EXCLUDED.status,
  transcript = EXCLUDED.transcript,
  metadata = EXCLUDED.metadata;

INSERT INTO bob_closed_items (id, framework, exam_part, cefr_level, variant_id, stimulus_audio_url, stimulus_text, stimulus_image_url, question, options, correct_key, explanation, source, created_at, skill, status, transcript, metadata)
VALUES
('f20b0abd-18ae-4ca3-9ba2-625afd1df743'::uuid, 'cefr', 'assessment_listening', 'b1', 'al-b1-07', '/listening/assessment/b1/al-b1-07.mp3', NULL, NULL, 'How did Marcus make friends in the new city?', '[{"key":"A","label":"Through his work colleagues"},{"key":"B","label":"By joining a football team"},{"key":"C","label":"At a language class"},{"key":"D","label":"Through social media"}]'::jsonb, 'B', 'Marcus made friends "after joining a local football team."', 'generated_then_curated', '2026-05-18T17:30:16.407296+00:00'::timestamptz, 'listening', 'enabled', 'Marcus moved to a new city for his job last year. He found it hard at first because he didn''t know anyone and the commute was long. However, after joining a local football team, he quickly made friends and now says he loves living there.', '{"topic":"social_life","voice":"adult_male","duration_estimate":17}'::jsonb),
('f2116f76-0ccf-49e7-b36e-b286898bd7d3'::uuid, 'cefr', 'assessment_reading', 'a2', 'ar-a2-06', NULL, 'The school trip to the science museum is on Friday 20th March. Students must arrive at school by 8:15 am. The coach leaves at 8:30. Please bring a packed lunch and wear comfortable shoes. No electronic devices.', NULL, 'What time does the coach leave?', '[{"key":"A","label":"8:00 am"},{"key":"B","label":"8:15 am"},{"key":"C","label":"8:30 am"},{"key":"D","label":"9:00 am"}]'::jsonb, 'C', 'The notice says "The coach leaves at 8:30."', 'generated_then_curated', '2026-05-18T18:31:46.992101+00:00'::timestamptz, 'reading', 'enabled', NULL, '{"genre":"information_text","topic":"school_trips","estimated_seconds":35}'::jsonb),
('f2307c6c-7a66-4354-b307-76a33c866b26'::uuid, 'cefr', 'assessment_reading', 'a2', 'ar-a2-04', NULL, 'Omar started learning the guitar six months ago. He practises for 30 minutes every evening. His teacher says he is making very good progress. Omar wants to play in the school concert next year.', NULL, 'What is Omar''s goal?', '[{"key":"A","label":"To buy a new guitar"},{"key":"B","label":"To become a music teacher"},{"key":"C","label":"To play in the school concert"},{"key":"D","label":"To practise for an hour a day"}]'::jsonb, 'C', 'The text says "Omar wants to play in the school concert next year."', 'generated_then_curated', '2026-05-18T18:31:46.992101+00:00'::timestamptz, 'reading', 'enabled', NULL, '{"genre":"personal_description","topic":"music_hobbies","estimated_seconds":35}'::jsonb),
('f2a1c252-db98-4558-808a-3752c38f3ba9'::uuid, 'cambridge', 'fce_listening_part1', 'b2', 'fl-p1-06', '/fce-listening-part1/fl-p1-06.mp3', NULL, NULL, 'What conclusion does the speaker draw about the four-day working week?', '[{"key":"A","label":"It consistently improves productivity across all industries"},{"key":"B","label":"Its success depends heavily on the nature of the work and organisation"},{"key":"C","label":"It is only practical in sectors where remote work is possible"}]'::jsonb, 'B', 'The speaker quotes the report''s authors warning against blanket conclusions and highlights sector and culture as key variables.', 'generated_then_curated', '2026-05-19T14:11:58.471575+00:00'::timestamptz, 'listening', 'enabled', 'The report released this morning challenges the assumption that reduced working hours automatically lead to lower productivity. Across fourteen companies in six countries, employees who shifted to a four-day week maintained or exceeded their previous output in eleven of those cases. The exceptions were two firms in logistics where real-time coordination requirements made condensed scheduling impractical. The study''s authors are careful to note that the model works differently depending on sector, management culture, and the degree to which tasks can be asynchronous. Blanket conclusions either way would be premature.', '{"topic":"current_affairs","voice":"adult_male","question_focus":"detail","estimated_seconds":48}'::jsonb),
('f50ccc8f-ee9f-4990-831f-9a3dfb42663c'::uuid, 'cefr', 'assessment_listening', 'a1', 'al-a1-07', '/listening/assessment/a1/al-a1-07.mp3', NULL, NULL, 'What kind of cake will the speaker have?', '[{"key":"A","label":"Vanilla"},{"key":"B","label":"Strawberry"},{"key":"C","label":"Lemon"},{"key":"D","label":"Chocolate"}]'::jsonb, 'D', 'The speaker says "My mum will make a chocolate cake."', 'generated_then_curated', '2026-05-18T17:30:16.407296+00:00'::timestamptz, 'listening', 'enabled', 'My birthday is in July. I am going to have a party. My mum will make a chocolate cake. I love chocolate!', '{"topic":"birthday","voice":"child_female","duration_estimate":10}'::jsonb),
('f53071dd-a31e-45d9-b288-5fb0025d3306'::uuid, 'cefr', 'assessment_listening', 'a2', 'al-a2-04', '/listening/assessment/a2/al-a2-04.mp3', NULL, NULL, 'Why did Sofia and her brother NOT watch the action film?', '[{"key":"A","label":"They didn''t like action films"},{"key":"B","label":"It was too expensive"},{"key":"C","label":"It was sold out"},{"key":"D","label":"It started too late"}]'::jsonb, 'C', 'The text says "it was sold out."', 'generated_then_curated', '2026-05-18T17:30:16.407296+00:00'::timestamptz, 'listening', 'enabled', 'Sofia and her brother went to the cinema last Saturday. They wanted to see the action film but it was sold out. They bought tickets for the comedy instead and really enjoyed it.', '{"topic":"leisure_cinema","voice":"teenager_female","duration_estimate":14}'::jsonb),
('f6839671-0326-4d58-a688-4787ef66bcc6'::uuid, 'cambridge', 'pet_listening_part2', 'b1', 'pl-p2-09', '/pet-listening-part2/pl-p2-09.mp3', NULL, NULL, 'What does the speaker most appreciate about the meal planning app?', '[{"key":"A","label":"It recommends popular restaurants nearby"},{"key":"B","label":"It automatically creates a shopping list for missing items"},{"key":"C","label":"It teaches her new cooking techniques"},{"key":"D","label":"It stores all her favourite recipes"}]'::jsonb, 'B', 'The speaker specifically highlights the automatic shopping list as what she really appreciates.', 'generated_then_curated', '2026-05-19T13:52:11.261222+00:00'::timestamptz, 'listening', 'enabled', 'Technology has completely changed the way I cook. Before, I''d spend ages flicking through cookbooks and never being sure if a recipe would turn out well. Now I use a meal planning app that suggests recipes based on what''s already in my fridge. What I really appreciate is that it automatically generates a shopping list for any ingredients I''m missing. I save both time and money because I don''t buy things I don''t need.', '{"topic":"technology_food","voice":"adult_female","estimated_seconds":22}'::jsonb),
('f98b9365-f07b-40aa-b889-7543ff1b8608'::uuid, 'cambridge', 'pet_listening_part2', 'b1', 'pl-p2-06', '/pet-listening-part2/pl-p2-06.mp3', NULL, NULL, 'What did most residents value most about community gardens?', '[{"key":"A","label":"Growing their own food"},{"key":"B","label":"Reducing their stress levels"},{"key":"C","label":"Meeting their neighbours"},{"key":"D","label":"Improving the neighbourhood''s appearance"}]'::jsonb, 'C', 'The majority valued community gardens primarily as a place to meet neighbours, not mainly for food or stress reduction.', 'generated_then_curated', '2026-05-19T13:52:11.261222+00:00'::timestamptz, 'listening', 'enabled', 'In this week''s environment segment, we''re looking at community gardens in urban areas. Researchers at Greenfield University interviewed residents living near community gardens and found that most people valued them primarily as a place to meet neighbours rather than for the food they produced. Several respondents also mentioned reduced stress levels. Only a small number said they visited mainly to grow their own vegetables.', '{"topic":"environment_community","voice":"adult_male","estimated_seconds":21}'::jsonb),
('fb88bd2c-484e-4a8a-88ed-c2d47362ea12'::uuid, 'cefr', 'assessment_reading', 'b2', 'ar-b2-07', NULL, 'Biomimicry — the practice of taking inspiration from nature to solve engineering problems — has produced remarkable innovations. Velcro was modelled on burr seeds; bullet trains were redesigned after the kingfisher''s beak to reduce noise; shark skin has inspired low-drag swimwear. Yet despite its apparent promise, biomimicry remains a niche field, largely because translating biological principles into manufacturable products is far more complex than it first appears.', NULL, 'What does the text suggest is the main limitation of biomimicry?', '[{"key":"A","label":"Nature does not offer enough examples"},{"key":"B","label":"It is too expensive to research"},{"key":"C","label":"Turning biological ideas into products is technically difficult"},{"key":"D","label":"Companies are not interested in the approach"}]'::jsonb, 'C', 'The text says it remains niche "because translating biological principles into manufacturable products is far more complex than it first appears."', 'generated_then_curated', '2026-05-18T18:31:46.992101+00:00'::timestamptz, 'reading', 'enabled', NULL, '{"genre":"academic_article","topic":"science_technology","estimated_seconds":60}'::jsonb),
('ff5987ad-c9f7-43de-be28-e2001681d7f2'::uuid, 'cambridge', 'pet_listening_part2', 'b1', 'pl-p2-10', '/pet-listening-part2/pl-p2-10.mp3', NULL, NULL, 'How did Tomas feel during his first weeks at university?', '[{"key":"A","label":"Excited to meet new people"},{"key":"B","label":"Lonely and isolated"},{"key":"C","label":"Bored by his course"},{"key":"D","label":"Unhappy with his accommodation"}]'::jsonb, 'B', 'Tomas suddenly felt very isolated having left his close family environment behind.', 'generated_then_curated', '2026-05-19T13:52:11.261222+00:00'::timestamptz, 'listening', 'enabled', 'Tomas moved to a new city for university last September. He found the first few weeks very difficult because he was used to a close-knit family environment and suddenly felt very isolated. He thought about going home but decided to push through. By November, after joining the university running club, he had made a solid group of friends and now says he wouldn''t change the experience for anything. He believes the challenge made him much more independent.', '{"topic":"family_independence","voice":"teenager_male","estimated_seconds":22}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  framework = EXCLUDED.framework,
  exam_part = EXCLUDED.exam_part,
  cefr_level = EXCLUDED.cefr_level,
  variant_id = EXCLUDED.variant_id,
  stimulus_audio_url = EXCLUDED.stimulus_audio_url,
  stimulus_text = EXCLUDED.stimulus_text,
  stimulus_image_url = EXCLUDED.stimulus_image_url,
  question = EXCLUDED.question,
  options = EXCLUDED.options,
  correct_key = EXCLUDED.correct_key,
  explanation = EXCLUDED.explanation,
  source = EXCLUDED.source,
  skill = EXCLUDED.skill,
  status = EXCLUDED.status,
  transcript = EXCLUDED.transcript,
  metadata = EXCLUDED.metadata;

-- ---------------------------------------------------------------------------
-- bob_app_config (2 rows — PLACEHOLDERS for production credentials)
-- ---------------------------------------------------------------------------
/*
 * WHY: worker_url must point to the production edge function URL, and
 * worker_auth must be the production project's service-role JWT. These values
 * are environment-specific and cannot be copied from dev. Fill them manually
 * after deploying the assessment-eval-worker edge function to production.
 * ON CONFLICT DO NOTHING ensures a re-run never overwrites already-set creds.
 */
INSERT INTO bob_app_config (key, value)
VALUES
  ('worker_url', 'https://twnefuvnapniswiktfbx.supabase.co/functions/v1/assessment-eval-worker'),
  ('worker_auth', 'PASTE_SERVICE_ROLE_JWT_HERE')
ON CONFLICT (key) DO NOTHING;


-- ---------------------------------------------------------------------------
-- Reset sequences for tables with bigint id
-- ---------------------------------------------------------------------------
SELECT setval('bob_vocabulary_id_seq', (SELECT COALESCE(MAX(id), 1) FROM bob_vocabulary));



COMMIT;
