-- Starters Part 1 (Pointing) generation prompt no longer invents vocabulary.
-- The server now pre-picks 4 words from bob_vocabulary (distinct categories)
-- and injects them as {WORD_1}..{WORD_4}. This kills the "always apple / cat
-- / book" few-shot anchoring problem and guarantees rotation across the full
-- official Cambridge YLE Pre A1 Starters wordlist.

UPDATE public.bob_prompts
SET
  variables = '["WORD_1","WORD_2","WORD_3","WORD_4"]'::jsonb,
  prompt_default = E'You are designing a Cambridge Starters Part 1 POINTING activity (Pre-A1) for children aged 6-9.\n\nThe four vocabulary items have already been chosen for you, in this order:\n  1. {WORD_1}\n  2. {WORD_2}\n  3. {WORD_3}\n  4. {WORD_4}\n\nFor EACH of these four words, in order, write ONE image scene prompt. Each scene prompt MUST describe 1-3 people (children or family members) interacting with or near the target item, so every illustration always shows humans — never an isolated object. Keep the target item visually dominant and easy to recognise. Vary the settings across the four scenes (home, classroom, park, kitchen, garden, street, beach, bedroom) so they feel different from each other.\n\nThen write FOUR pointing cues, one per word, of the form "Point to the X." where X is the word as a child would naturally say it. target_index matches the position in the list (0-3).\n\nOUTPUT minified JSON only, no commentary:\n{\n  "options": ["{WORD_1}", "{WORD_2}", "{WORD_3}", "{WORD_4}"],\n  "option_image_prompts": [\n    "<scene 1 — people interacting with {WORD_1}>",\n    "<scene 2 — people interacting with {WORD_2}>",\n    "<scene 3 — people interacting with {WORD_3}>",\n    "<scene 4 — people interacting with {WORD_4}>"\n  ],\n  "cues": [\n    { "text": "Point to the {WORD_1}.", "target_index": 0 },\n    { "text": "Point to the {WORD_2}.", "target_index": 1 },\n    { "text": "Point to the {WORD_3}.", "target_index": 2 },\n    { "text": "Point to the {WORD_4}.", "target_index": 3 }\n  ]\n}',
  prompt_current = E'You are designing a Cambridge Starters Part 1 POINTING activity (Pre-A1) for children aged 6-9.\n\nThe four vocabulary items have already been chosen for you, in this order:\n  1. {WORD_1}\n  2. {WORD_2}\n  3. {WORD_3}\n  4. {WORD_4}\n\nFor EACH of these four words, in order, write ONE image scene prompt. Each scene prompt MUST describe 1-3 people (children or family members) interacting with or near the target item, so every illustration always shows humans — never an isolated object. Keep the target item visually dominant and easy to recognise. Vary the settings across the four scenes (home, classroom, park, kitchen, garden, street, beach, bedroom) so they feel different from each other.\n\nThen write FOUR pointing cues, one per word, of the form "Point to the X." where X is the word as a child would naturally say it. target_index matches the position in the list (0-3).\n\nOUTPUT minified JSON only, no commentary:\n{\n  "options": ["{WORD_1}", "{WORD_2}", "{WORD_3}", "{WORD_4}"],\n  "option_image_prompts": [\n    "<scene 1 — people interacting with {WORD_1}>",\n    "<scene 2 — people interacting with {WORD_2}>",\n    "<scene 3 — people interacting with {WORD_3}>",\n    "<scene 4 — people interacting with {WORD_4}>"\n  ],\n  "cues": [\n    { "text": "Point to the {WORD_1}.", "target_index": 0 },\n    { "text": "Point to the {WORD_2}.", "target_index": 1 },\n    { "text": "Point to the {WORD_3}.", "target_index": 2 },\n    { "text": "Point to the {WORD_4}.", "target_index": 3 }\n  ]\n}'
WHERE prompt_key = 'cambridge_starters_part1_a1_generation';
