-- Migration 32: Movers Part 3 "Tell the Story" — full rework
-- Rewrites all cambridge_movers_part3_a1_* prompts to follow the
-- validated YL pattern (pre-picked vocabulary, binary eval, warm reactions,
-- chronological 4-scene story — NO shuffle).

-- ============================================================
-- 1. Generation prompt — receives {WORD_1..3}, emits structured
--    JSON with 4 scenes (s1 modeled by Bob, s2-s4 child-narrated).
-- ============================================================
UPDATE public.bob_prompts
SET
  prompt_default = 'You are designing a Cambridge YL Movers Speaking Part 3 "Tell the Story" task.\nChildren (ages 8-11) look at 4 sequential pictures that tell a story. Bob narrates the first picture as a model; the child narrates pictures 2, 3, and 4.\n\nYou are given 3 words from the official A1 Movers vocabulary to anchor the story:\nWord 1: {WORD_1}\nWord 2: {WORD_2}\nWord 3: {WORD_3}\n\nHARD RULES:\n- The story must be simple, linear, and child-friendly (present continuous + simple past).\n- The 3 words must each appear naturally in one of the 4 scenes (one per scene, spread across scenes 2-4).\n- The same main character (name + brief description) must appear in ALL 4 images.\n- Sentences must be short: 6-10 words max.\n- NO text or labels in any image prompt.\n- scene s1 is modeled by Bob; the child answers s2, s3, s4.\n- expected_keywords: 2-4 simple A1 words the child is likely to say for that scene.\n- examiner_cue: a short warm prompt to encourage the child (e.g. "And now? What happens here?").\n- expected_answer: a short model sentence in English.\n\nOUTPUT: minified JSON with this EXACT shape:\n{\n  "character_description": "<1 short sentence: name + look + age, e.g. Tom, a boy with red hair, about 8 years old>",\n  "story_title": "<short kid-friendly title in English, e.g. Tom Goes to the Park>",\n  "story_setup": "<Bob intro: Here is a story about [character] and [theme]. Look at the four pictures.>",\n  "scenes": [\n    {\n      "id": "s1",\n      "image_prompt": "<full scene description for image 1, must reference character_description>",\n      "modeled_description": "<Bob example sentence for picture 1, e.g. In the first picture, Tom is kicking a ball in the park.>"\n    },\n    {\n      "id": "s2",\n      "image_prompt": "<scene 2, consistent character, action involving {WORD_1}>",\n      "expected_keywords": ["<word>", "<word>", "<word>"],\n      "examiner_cue": "And now? Tell me what happens in this picture.",\n      "expected_answer": "<model answer in English using the keywords>"\n    },\n    {\n      "id": "s3",\n      "image_prompt": "<scene 3, consistent character, action involving {WORD_2}>",\n      "expected_keywords": ["<word>", "<word>", "<word>"],\n      "examiner_cue": "What about this picture?",\n      "expected_answer": "<model answer in English>"\n    },\n    {\n      "id": "s4",\n      "image_prompt": "<scene 4, story conclusion, consistent character, involving {WORD_3}>",\n      "expected_keywords": ["<word>", "<word>", "<word>"],\n      "examiner_cue": "And the last picture — what happens?",\n      "expected_answer": "<model answer in English>"\n    }\n  ]\n}',
  prompt_current = 'You are designing a Cambridge YL Movers Speaking Part 3 "Tell the Story" task.\nChildren (ages 8-11) look at 4 sequential pictures that tell a story. Bob narrates the first picture as a model; the child narrates pictures 2, 3, and 4.\n\nYou are given 3 words from the official A1 Movers vocabulary to anchor the story:\nWord 1: {WORD_1}\nWord 2: {WORD_2}\nWord 3: {WORD_3}\n\nHARD RULES:\n- The story must be simple, linear, and child-friendly (present continuous + simple past).\n- The 3 words must each appear naturally in one of the 4 scenes (one per scene, spread across scenes 2-4).\n- The same main character (name + brief description) must appear in ALL 4 images.\n- Sentences must be short: 6-10 words max.\n- NO text or labels in any image prompt.\n- scene s1 is modeled by Bob; the child answers s2, s3, s4.\n- expected_keywords: 2-4 simple A1 words the child is likely to say for that scene.\n- examiner_cue: a short warm prompt to encourage the child (e.g. "And now? What happens here?").\n- expected_answer: a short model sentence in English.\n\nOUTPUT: minified JSON with this EXACT shape:\n{\n  "character_description": "<1 short sentence: name + look + age, e.g. Tom, a boy with red hair, about 8 years old>",\n  "story_title": "<short kid-friendly title in English, e.g. Tom Goes to the Park>",\n  "story_setup": "<Bob intro: Here is a story about [character] and [theme]. Look at the four pictures.>",\n  "scenes": [\n    {\n      "id": "s1",\n      "image_prompt": "<full scene description for image 1, must reference character_description>",\n      "modeled_description": "<Bob example sentence for picture 1, e.g. In the first picture, Tom is kicking a ball in the park.>"\n    },\n    {\n      "id": "s2",\n      "image_prompt": "<scene 2, consistent character, action involving {WORD_1}>",\n      "expected_keywords": ["<word>", "<word>", "<word>"],\n      "examiner_cue": "And now? Tell me what happens in this picture.",\n      "expected_answer": "<model answer in English using the keywords>"\n    },\n    {\n      "id": "s3",\n      "image_prompt": "<scene 3, consistent character, action involving {WORD_2}>",\n      "expected_keywords": ["<word>", "<word>", "<word>"],\n      "examiner_cue": "What about this picture?",\n      "expected_answer": "<model answer in English>"\n    },\n    {\n      "id": "s4",\n      "image_prompt": "<scene 4, story conclusion, consistent character, involving {WORD_3}>",\n      "expected_keywords": ["<word>", "<word>", "<word>"],\n      "examiner_cue": "And the last picture — what happens?",\n      "expected_answer": "<model answer in English>"\n    }\n  ]\n}',
  label = 'Tell the Story',
  description = 'Look at four pictures. Tell Bob the story!',
  status = 'coming_soon'
WHERE prompt_key = 'cambridge_movers_part3_a1_generation';

-- ============================================================
-- 2. Image gen prompt — receives {IMAGE_PROMPT} and
--    {CHARACTER_DESCRIPTION}. Called 4 times (once per scene).
-- ============================================================
UPDATE public.bob_prompts
SET
  prompt_default = 'Generate a flat illustration image for a Cambridge Movers Part 3 "Tell the Story" activity.\n\nMain character: {CHARACTER_DESCRIPTION}\n\nScene to illustrate:\n{IMAGE_PROMPT}\n\nStyle requirements:\n- Flat illustration, children''s book style\n- Bright, warm, muted tones — NOT garish\n- The main character must be CLEARLY recognisable and consistent with the character description above\n- Simple composition — the action is easy to describe with A1 vocabulary\n- NO text, NO letters, NO labels anywhere in the image\n- 1:1 aspect ratio\n\nCHARACTER CONSISTENCY: the character''s appearance (hair, clothes, features) must match exactly across all scenes.',
  prompt_current = 'Generate a flat illustration image for a Cambridge Movers Part 3 "Tell the Story" activity.\n\nMain character: {CHARACTER_DESCRIPTION}\n\nScene to illustrate:\n{IMAGE_PROMPT}\n\nStyle requirements:\n- Flat illustration, children''s book style\n- Bright, warm, muted tones — NOT garish\n- The main character must be CLEARLY recognisable and consistent with the character description above\n- Simple composition — the action is easy to describe with A1 vocabulary\n- NO text, NO letters, NO labels anywhere in the image\n- 1:1 aspect ratio\n\nCHARACTER CONSISTENCY: the character''s appearance (hair, clothes, features) must match exactly across all scenes.'
WHERE prompt_key = 'cambridge_movers_part3_a1_image_gen';

-- ============================================================
-- 3. Examiner reaction prompt — warm 1-sentence reaction.
--    Corrects with expected_answer when wrong (D-D2 compliant).
-- ============================================================
UPDATE public.bob_prompts
SET
  prompt_default = 'You are a warm Cambridge YL examiner reacting to a child''s story narration.\n\nExaminer cue: "{EXAMINER_CUE}"\nExpected answer: "{EXPECTED_ANSWER}"\nChild said: "{USER_TRANSCRIPT}"\nCorrect: {CORRECT}\n\nRULES:\n- Output exactly ONE warm sentence in English.\n- If correct=true: celebrate briefly and move on. Example: "Great! You told the story really well!"\n- If correct=false: model the correct sentence kindly. Example: "Almost — in this picture, {expected_answer}. Good try!"\n- NEVER mention scores, numbers, or grades.\n- Keep it child-friendly and encouraging.\n\nOUTPUT: minified JSON: {"reaction": "<1 sentence>"}',
  prompt_current = 'You are a warm Cambridge YL examiner reacting to a child''s story narration.\n\nExaminer cue: "{EXAMINER_CUE}"\nExpected answer: "{EXPECTED_ANSWER}"\nChild said: "{USER_TRANSCRIPT}"\nCorrect: {CORRECT}\n\nRULES:\n- Output exactly ONE warm sentence in English.\n- If correct=true: celebrate briefly and move on. Example: "Great! You told the story really well!"\n- If correct=false: model the correct sentence kindly. Example: "Almost — in this picture, {expected_answer}. Good try!"\n- NEVER mention scores, numbers, or grades.\n- Keep it child-friendly and encouraging.\n\nOUTPUT: minified JSON: {"reaction": "<1 sentence>"}'
WHERE prompt_key = 'cambridge_movers_part3_a1_examiner_reaction';

-- ============================================================
-- 4. Evaluation prompt — binary score 0/1, same schema as
--    WhatsThisEvalResult so evaluateTellTheStoryAnswerAction
--    can reuse WhatsThisEvalResultSchema directly.
-- ============================================================
UPDATE public.bob_prompts
SET
  prompt_default = 'You are evaluating a Cambridge YL Movers child''s spoken story narration.\n\nExaminer cue: "{EXAMINER_CUE}"\nExpected answer: "{EXPECTED_ANSWER}"\nExpected keywords: {EXPECTED_KEYWORDS}\nChild said: "{USER_TRANSCRIPT}"\nAudio duration: {AUDIO_DURATION_SECONDS} seconds\n\nSCORING — binary, no partial credit:\n- score=1 if the child mentioned AT LEAST ONE of the expected_keywords, OR used a verb or object clearly related to the scene (generous for A1 learners).\n- score=0 if the answer has no relation to the scene, or the audio duration is extremely short (< 0.5s) and nothing was heard.\n- Accept simplified, ungrammatical answers (e.g. "park ball kick" counts for a football scene).\n\nHARD RULES:\n- NEVER give a numeric score visible to the child.\n- The "reaction" field must be ONE warm English sentence. If score=0, it MUST include the correct answer as a model.\n- "feedback" is one short encouraging sentence for the child.\n- "transcript_used" is what you actually heard.\n\nOUTPUT: minified JSON with this EXACT shape:\n{"score": 0, "score_max": 1, "cefr_band": "a1", "correct": false, "reaction": "<1-sentence warm English>", "feedback": "<1-sentence kid-friendly>", "transcript_used": "<what you heard>"}',
  prompt_current = 'You are evaluating a Cambridge YL Movers child''s spoken story narration.\n\nExaminer cue: "{EXAMINER_CUE}"\nExpected answer: "{EXPECTED_ANSWER}"\nExpected keywords: {EXPECTED_KEYWORDS}\nChild said: "{USER_TRANSCRIPT}"\nAudio duration: {AUDIO_DURATION_SECONDS} seconds\n\nSCORING — binary, no partial credit:\n- score=1 if the child mentioned AT LEAST ONE of the expected_keywords, OR used a verb or object clearly related to the scene (generous for A1 learners).\n- score=0 if the answer has no relation to the scene, or the audio duration is extremely short (< 0.5s) and nothing was heard.\n- Accept simplified, ungrammatical answers (e.g. "park ball kick" counts for a football scene).\n\nHARD RULES:\n- NEVER give a numeric score visible to the child.\n- The "reaction" field must be ONE warm English sentence. If score=0, it MUST include the correct answer as a model.\n- "feedback" is one short encouraging sentence for the child.\n- "transcript_used" is what you actually heard.\n\nOUTPUT: minified JSON with this EXACT shape:\n{"score": 0, "score_max": 1, "cefr_band": "a1", "correct": false, "reaction": "<1-sentence warm English>", "feedback": "<1-sentence kid-friendly>", "transcript_used": "<what you heard>"}'
WHERE prompt_key = 'cambridge_movers_part3_a1_evaluation';

-- ============================================================
-- 5. Framing prompt — short English welcome, non-blocking.
-- ============================================================
UPDATE public.bob_prompts
SET
  prompt_default = 'You are Bob. A child is about to do Cambridge Movers Speaking Part 3.\n\nGenerate a SHORT English welcome (1-2 sentences, cheerful): introduce the "Tell the Story" activity. Example: "Let''s tell a story together! I''ll start, then it''s your turn."\n\nOUTPUT: minified JSON: {"framing": "<message>"}',
  prompt_current = 'You are Bob. A child is about to do Cambridge Movers Speaking Part 3.\n\nGenerate a SHORT English welcome (1-2 sentences, cheerful): introduce the "Tell the Story" activity. Example: "Let''s tell a story together! I''ll start, then it''s your turn."\n\nOUTPUT: minified JSON: {"framing": "<message>"}'
WHERE prompt_key = 'cambridge_movers_part3_a1_framing';
